/**
 * Balance simulator (DEV_PLAN Phase 1): auto-plays thousands of games with
 * the greedy bot and reports weeks-to-win distributions per preset.
 * Run: pnpm tsx scripts/balance-sim.ts [games-per-preset]
 */

import { greedyPlan } from "../packages/engine/src/bots/greedy";
import { GOAL_PRESETS } from "../packages/engine/src/config/balance";
import { resolveWeek } from "../packages/engine/src/resolve";
import { initialGameState } from "../packages/engine/src/state";
import type { Action, GameState } from "../packages/engine/src/types";

const GAMES = Number(process.argv[2] ?? 2000);
const PLAYERS = 4;
const HARD_CAP = 60; // sim cap beyond game cap to observe tail

interface SimResult {
  weeks: number;
  finishedByGoals: boolean;
}

function simulate(preset: keyof typeof GOAL_PRESETS, seed: number): SimResult {
  let state: GameState = initialGameState(seed, PLAYERS, {
    goals: { ...GOAL_PRESETS[preset] },
    maxWeeks: HARD_CAP,
    planTimerSeconds: 90
  });
  for (let w = 1; w <= HARD_CAP; w++) {
    const plans = new Map<number, Action[]>();
    for (let s = 0; s < PLAYERS; s++) plans.set(s, greedyPlan(state, s));
    const result = resolveWeek(state, plans);
    if (result.winnerSlot !== undefined && result.players.some((p) => p.goalProgress.achievedAll)) {
      return { weeks: w, finishedByGoals: true };
    }
    state = result.nextState;
  }
  return { weeks: HARD_CAP, finishedByGoals: false };
}

function pct(arr: number[], q: number): number {
  const sorted = [...arr].sort((a, b) => a - b);
  return sorted[Math.min(sorted.length - 1, Math.floor(q * sorted.length))]!;
}

console.log(`# Fast Lane balance sim — ${GAMES} games/preset, ${PLAYERS} bots\n`);
const report: string[] = [
  `# Balance Simulation Report`,
  ``,
  `Generated by \`scripts/balance-sim.ts\` — ${GAMES} games per preset, ${PLAYERS} greedy bots per game.`,
  ``
];

for (const preset of ["quick", "classic", "marathon"] as const) {
  const weeks: number[] = [];
  let unfinished = 0;
  for (let g = 0; g < GAMES; g++) {
    const r = simulate(preset, g * 104729 + 7);
    weeks.push(r.weeks);
    if (!r.finishedByGoals) unfinished++;
  }
  const mean = (weeks.reduce((a, b) => a + b, 0) / weeks.length).toFixed(1);
  const line = `${preset.padEnd(9)} mean=${mean}w  p25=${pct(weeks, 0.25)}  p50=${pct(weeks, 0.5)}  p75=${pct(weeks, 0.75)}  p95=${pct(weeks, 0.95)}  unfinished@${HARD_CAP}w=${((unfinished / GAMES) * 100).toFixed(1)}%`;
  console.log(line);
  report.push(`- **${preset}**: mean ${mean} weeks · p25 ${pct(weeks, 0.25)} · p50 ${pct(weeks, 0.5)} · p75 ${pct(weeks, 0.75)} · p95 ${pct(weeks, 0.95)} · unfinished at ${HARD_CAP}w: ${((unfinished / GAMES) * 100).toFixed(1)}%`);
}

report.push(``, `Target (DEV_PLAN Phase 1): Quick ≈ 10–14 weeks median.`);

import { writeFileSync } from "node:fs";
writeFileSync("docs/balance-sim-report.md", report.join("\n") + "\n");
console.log("\nreport → docs/balance-sim-report.md");
